/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowRouteImport } from './routes/how'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LoadingScreensRouteImport } from './routes/loading-screens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObfuscatorsRouteImport } from './routes/obfuscators'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TosRouteImport } from './routes/tos'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as DocsLoadingRouteImport } from './routes/docs.loading'
import { Route as FeaturesKeySystemGuiRouteImport } from './routes/features.key-system-gui'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated/dashboard/api-keys'
import { Route as AuthenticatedDashboardBatchesRouteImport } from './routes/_authenticated/dashboard/batches'
import { Route as AuthenticatedDashboardHwidRouteImport } from './routes/_authenticated/dashboard/hwid'
import { Route as AuthenticatedDashboardKeysRouteImport } from './routes/_authenticated/dashboard/keys'
import { Route as AuthenticatedDashboardObfuscateRouteImport } from './routes/_authenticated/dashboard/obfuscate'
import { Route as AuthenticatedDashboardPanelsRouteImport } from './routes/_authenticated/dashboard/panels'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as ApiPublicObfuscateRouteImport } from './routes/api/public/obfuscate'
import { Route as ScriptsHostedPublicIdDotluaRouteImport } from './routes/scripts.hosted.$publicId[.]lua'
import { Route as ScriptsRawPublicIdDotluaRouteImport } from './routes/scripts.raw.$publicId[.]lua'
import { Route as AuthenticatedDashboardScriptsIndexRouteImport } from './routes/_authenticated/dashboard/scripts/index'
import { Route as AuthenticatedDashboardScriptsIdRouteImport } from './routes/_authenticated/dashboard/scripts/$id'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth/login'
import { Route as ApiPublicDiscordInteractionsRouteImport } from './routes/api/public/discord/interactions'
import { Route as ApiPublicDiscordRegisterCommandsRouteImport } from './routes/api/public/discord/register-commands'
import { Route as ApiPublicLoaderPublicIdRouteImport } from './routes/api/public/loader/$publicId'
import { Route as ApiPublicRPublicIdRouteImport } from './routes/api/public/r/$publicId'
import { Route as ApiPublicDiscordOauthCallbackRouteImport } from './routes/api/public/discord/oauth/callback'
import { Route as ApiPublicDiscordOauthStartRouteImport } from './routes/api/public/discord/oauth/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingScreensRoute = LoadingScreensRouteImport.update({
  id: '/loading-screens',
  path: '/loading-screens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObfuscatorsRoute = ObfuscatorsRouteImport.update({
  id: '/obfuscators',
  path: '/obfuscators',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLoadingRoute = DocsLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => DocsRoute,
} as any)
const FeaturesKeySystemGuiRoute = FeaturesKeySystemGuiRouteImport.update({
  id: '/key-system-gui',
  path: '/key-system-gui',
  getParentRoute: () => FeaturesRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/dashboard/api-keys',
    path: '/dashboard/api-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBatchesRoute =
  AuthenticatedDashboardBatchesRouteImport.update({
    id: '/dashboard/batches',
    path: '/dashboard/batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardHwidRoute =
  AuthenticatedDashboardHwidRouteImport.update({
    id: '/dashboard/hwid',
    path: '/dashboard/hwid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardKeysRoute =
  AuthenticatedDashboardKeysRouteImport.update({
    id: '/dashboard/keys',
    path: '/dashboard/keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardObfuscateRoute =
  AuthenticatedDashboardObfuscateRouteImport.update({
    id: '/dashboard/obfuscate',
    path: '/dashboard/obfuscate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPanelsRoute =
  AuthenticatedDashboardPanelsRouteImport.update({
    id: '/dashboard/panels',
    path: '/dashboard/panels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicObfuscateRoute = ApiPublicObfuscateRouteImport.update({
  id: '/api/public/obfuscate',
  path: '/api/public/obfuscate',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsHostedPublicIdDotluaRoute =
  ScriptsHostedPublicIdDotluaRouteImport.update({
    id: '/scripts/hosted/$publicId.lua',
    path: '/scripts/hosted/$publicId.lua',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScriptsRawPublicIdDotluaRoute =
  ScriptsRawPublicIdDotluaRouteImport.update({
    id: '/scripts/raw/$publicId.lua',
    path: '/scripts/raw/$publicId.lua',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardScriptsIndexRoute =
  AuthenticatedDashboardScriptsIndexRouteImport.update({
    id: '/dashboard/scripts/',
    path: '/dashboard/scripts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardScriptsIdRoute =
  AuthenticatedDashboardScriptsIdRouteImport.update({
    id: '/dashboard/scripts/$id',
    path: '/dashboard/scripts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordInteractionsRoute =
  ApiPublicDiscordInteractionsRouteImport.update({
    id: '/api/public/discord/interactions',
    path: '/api/public/discord/interactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordRegisterCommandsRoute =
  ApiPublicDiscordRegisterCommandsRouteImport.update({
    id: '/api/public/discord/register-commands',
    path: '/api/public/discord/register-commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLoaderPublicIdRoute = ApiPublicLoaderPublicIdRouteImport.update({
  id: '/api/public/loader/$publicId',
  path: '/api/public/loader/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRPublicIdRoute = ApiPublicRPublicIdRouteImport.update({
  id: '/api/public/r/$publicId',
  path: '/api/public/r/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordOauthCallbackRoute =
  ApiPublicDiscordOauthCallbackRouteImport.update({
    id: '/api/public/discord/oauth/callback',
    path: '/api/public/discord/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordOauthStartRoute =
  ApiPublicDiscordOauthStartRouteImport.update({
    id: '/api/public/discord/oauth/start',
    path: '/api/public/discord/oauth/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/commands': typeof CommandsRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRouteWithChildren
  '/how': typeof HowRoute
  '/keys': typeof KeysRoute
  '/loading-screens': typeof LoadingScreensRoute
  '/login': typeof LoginRoute
  '/obfuscators': typeof ObfuscatorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/api/docs': typeof ApiDocsRoute
  '/docs/loading': typeof DocsLoadingRoute
  '/features/key-system-gui': typeof FeaturesKeySystemGuiRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/batches': typeof AuthenticatedDashboardBatchesRoute
  '/dashboard/hwid': typeof AuthenticatedDashboardHwidRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/obfuscate': typeof AuthenticatedDashboardObfuscateRoute
  '/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/obfuscate': typeof ApiPublicObfuscateRoute
  '/scripts/hosted/$publicId.lua': typeof ScriptsHostedPublicIdDotluaRoute
  '/scripts/raw/$publicId.lua': typeof ScriptsRawPublicIdDotluaRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/scripts/$id': typeof AuthenticatedDashboardScriptsIdRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/loader/$publicId': typeof ApiPublicLoaderPublicIdRoute
  '/api/public/r/$publicId': typeof ApiPublicRPublicIdRoute
  '/dashboard/scripts/': typeof AuthenticatedDashboardScriptsIndexRoute
  '/api/public/discord/oauth/callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord/oauth/start': typeof ApiPublicDiscordOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/commands': typeof CommandsRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRouteWithChildren
  '/how': typeof HowRoute
  '/keys': typeof KeysRoute
  '/loading-screens': typeof LoadingScreensRoute
  '/login': typeof LoginRoute
  '/obfuscators': typeof ObfuscatorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/api/docs': typeof ApiDocsRoute
  '/docs/loading': typeof DocsLoadingRoute
  '/features/key-system-gui': typeof FeaturesKeySystemGuiRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/batches': typeof AuthenticatedDashboardBatchesRoute
  '/dashboard/hwid': typeof AuthenticatedDashboardHwidRoute
  '/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/dashboard/obfuscate': typeof AuthenticatedDashboardObfuscateRoute
  '/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/obfuscate': typeof ApiPublicObfuscateRoute
  '/scripts/hosted/$publicId.lua': typeof ScriptsHostedPublicIdDotluaRoute
  '/scripts/raw/$publicId.lua': typeof ScriptsRawPublicIdDotluaRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/scripts/$id': typeof AuthenticatedDashboardScriptsIdRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/loader/$publicId': typeof ApiPublicLoaderPublicIdRoute
  '/api/public/r/$publicId': typeof ApiPublicRPublicIdRoute
  '/dashboard/scripts': typeof AuthenticatedDashboardScriptsIndexRoute
  '/api/public/discord/oauth/callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord/oauth/start': typeof ApiPublicDiscordOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/commands': typeof CommandsRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRouteWithChildren
  '/how': typeof HowRoute
  '/keys': typeof KeysRoute
  '/loading-screens': typeof LoadingScreensRoute
  '/login': typeof LoginRoute
  '/obfuscators': typeof ObfuscatorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tos': typeof TosRoute
  '/api/docs': typeof ApiDocsRoute
  '/docs/loading': typeof DocsLoadingRoute
  '/features/key-system-gui': typeof FeaturesKeySystemGuiRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/batches': typeof AuthenticatedDashboardBatchesRoute
  '/_authenticated/dashboard/hwid': typeof AuthenticatedDashboardHwidRoute
  '/_authenticated/dashboard/keys': typeof AuthenticatedDashboardKeysRoute
  '/_authenticated/dashboard/obfuscate': typeof AuthenticatedDashboardObfuscateRoute
  '/_authenticated/dashboard/panels': typeof AuthenticatedDashboardPanelsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/api/public/obfuscate': typeof ApiPublicObfuscateRoute
  '/scripts/hosted/$publicId.lua': typeof ScriptsHostedPublicIdDotluaRoute
  '/scripts/raw/$publicId.lua': typeof ScriptsRawPublicIdDotluaRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/scripts/$id': typeof AuthenticatedDashboardScriptsIdRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/discord/interactions': typeof ApiPublicDiscordInteractionsRoute
  '/api/public/discord/register-commands': typeof ApiPublicDiscordRegisterCommandsRoute
  '/api/public/loader/$publicId': typeof ApiPublicLoaderPublicIdRoute
  '/api/public/r/$publicId': typeof ApiPublicRPublicIdRoute
  '/_authenticated/dashboard/scripts/': typeof AuthenticatedDashboardScriptsIndexRoute
  '/api/public/discord/oauth/callback': typeof ApiPublicDiscordOauthCallbackRoute
  '/api/public/discord/oauth/start': typeof ApiPublicDiscordOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/changelog'
    | '/commands'
    | '/docs'
    | '/faq'
    | '/features'
    | '/how'
    | '/keys'
    | '/loading-screens'
    | '/login'
    | '/obfuscators'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/tos'
    | '/api/docs'
    | '/docs/loading'
    | '/features/key-system-gui'
    | '/dashboard/api-keys'
    | '/dashboard/batches'
    | '/dashboard/hwid'
    | '/dashboard/keys'
    | '/dashboard/obfuscate'
    | '/dashboard/panels'
    | '/dashboard/settings'
    | '/api/public/obfuscate'
    | '/scripts/hosted/$publicId.lua'
    | '/scripts/raw/$publicId.lua'
    | '/dashboard/'
    | '/dashboard/scripts/$id'
    | '/api/public/auth/login'
    | '/api/public/discord/interactions'
    | '/api/public/discord/register-commands'
    | '/api/public/loader/$publicId'
    | '/api/public/r/$publicId'
    | '/dashboard/scripts/'
    | '/api/public/discord/oauth/callback'
    | '/api/public/discord/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/changelog'
    | '/commands'
    | '/docs'
    | '/faq'
    | '/features'
    | '/how'
    | '/keys'
    | '/loading-screens'
    | '/login'
    | '/obfuscators'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/tos'
    | '/api/docs'
    | '/docs/loading'
    | '/features/key-system-gui'
    | '/dashboard/api-keys'
    | '/dashboard/batches'
    | '/dashboard/hwid'
    | '/dashboard/keys'
    | '/dashboard/obfuscate'
    | '/dashboard/panels'
    | '/dashboard/settings'
    | '/api/public/obfuscate'
    | '/scripts/hosted/$publicId.lua'
    | '/scripts/raw/$publicId.lua'
    | '/dashboard'
    | '/dashboard/scripts/$id'
    | '/api/public/auth/login'
    | '/api/public/discord/interactions'
    | '/api/public/discord/register-commands'
    | '/api/public/loader/$publicId'
    | '/api/public/r/$publicId'
    | '/dashboard/scripts'
    | '/api/public/discord/oauth/callback'
    | '/api/public/discord/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/changelog'
    | '/commands'
    | '/docs'
    | '/faq'
    | '/features'
    | '/how'
    | '/keys'
    | '/loading-screens'
    | '/login'
    | '/obfuscators'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/tos'
    | '/api/docs'
    | '/docs/loading'
    | '/features/key-system-gui'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/batches'
    | '/_authenticated/dashboard/hwid'
    | '/_authenticated/dashboard/keys'
    | '/_authenticated/dashboard/obfuscate'
    | '/_authenticated/dashboard/panels'
    | '/_authenticated/dashboard/settings'
    | '/api/public/obfuscate'
    | '/scripts/hosted/$publicId.lua'
    | '/scripts/raw/$publicId.lua'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/scripts/$id'
    | '/api/public/auth/login'
    | '/api/public/discord/interactions'
    | '/api/public/discord/register-commands'
    | '/api/public/loader/$publicId'
    | '/api/public/r/$publicId'
    | '/_authenticated/dashboard/scripts/'
    | '/api/public/discord/oauth/callback'
    | '/api/public/discord/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  CommandsRoute: typeof CommandsRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  HowRoute: typeof HowRoute
  KeysRoute: typeof KeysRoute
  LoadingScreensRoute: typeof LoadingScreensRoute
  LoginRoute: typeof LoginRoute
  ObfuscatorsRoute: typeof ObfuscatorsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TosRoute: typeof TosRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiPublicObfuscateRoute: typeof ApiPublicObfuscateRoute
  ScriptsHostedPublicIdDotluaRoute: typeof ScriptsHostedPublicIdDotluaRoute
  ScriptsRawPublicIdDotluaRoute: typeof ScriptsRawPublicIdDotluaRoute
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicDiscordInteractionsRoute: typeof ApiPublicDiscordInteractionsRoute
  ApiPublicDiscordRegisterCommandsRoute: typeof ApiPublicDiscordRegisterCommandsRoute
  ApiPublicLoaderPublicIdRoute: typeof ApiPublicLoaderPublicIdRoute
  ApiPublicRPublicIdRoute: typeof ApiPublicRPublicIdRoute
  ApiPublicDiscordOauthCallbackRoute: typeof ApiPublicDiscordOauthCallbackRoute
  ApiPublicDiscordOauthStartRoute: typeof ApiPublicDiscordOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading-screens': {
      id: '/loading-screens'
      path: '/loading-screens'
      fullPath: '/loading-screens'
      preLoaderRoute: typeof LoadingScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obfuscators': {
      id: '/obfuscators'
      path: '/obfuscators'
      fullPath: '/obfuscators'
      preLoaderRoute: typeof ObfuscatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/loading': {
      id: '/docs/loading'
      path: '/loading'
      fullPath: '/docs/loading'
      preLoaderRoute: typeof DocsLoadingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/features/key-system-gui': {
      id: '/features/key-system-gui'
      path: '/key-system-gui'
      fullPath: '/features/key-system-gui'
      preLoaderRoute: typeof FeaturesKeySystemGuiRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/batches': {
      id: '/_authenticated/dashboard/batches'
      path: '/dashboard/batches'
      fullPath: '/dashboard/batches'
      preLoaderRoute: typeof AuthenticatedDashboardBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/hwid': {
      id: '/_authenticated/dashboard/hwid'
      path: '/dashboard/hwid'
      fullPath: '/dashboard/hwid'
      preLoaderRoute: typeof AuthenticatedDashboardHwidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/keys': {
      id: '/_authenticated/dashboard/keys'
      path: '/dashboard/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof AuthenticatedDashboardKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/obfuscate': {
      id: '/_authenticated/dashboard/obfuscate'
      path: '/dashboard/obfuscate'
      fullPath: '/dashboard/obfuscate'
      preLoaderRoute: typeof AuthenticatedDashboardObfuscateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/panels': {
      id: '/_authenticated/dashboard/panels'
      path: '/dashboard/panels'
      fullPath: '/dashboard/panels'
      preLoaderRoute: typeof AuthenticatedDashboardPanelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/obfuscate': {
      id: '/api/public/obfuscate'
      path: '/api/public/obfuscate'
      fullPath: '/api/public/obfuscate'
      preLoaderRoute: typeof ApiPublicObfuscateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/hosted/$publicId.lua': {
      id: '/scripts/hosted/$publicId.lua'
      path: '/scripts/hosted/$publicId.lua'
      fullPath: '/scripts/hosted/$publicId.lua'
      preLoaderRoute: typeof ScriptsHostedPublicIdDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/raw/$publicId.lua': {
      id: '/scripts/raw/$publicId.lua'
      path: '/scripts/raw/$publicId.lua'
      fullPath: '/scripts/raw/$publicId.lua'
      preLoaderRoute: typeof ScriptsRawPublicIdDotluaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/scripts/': {
      id: '/_authenticated/dashboard/scripts/'
      path: '/dashboard/scripts'
      fullPath: '/dashboard/scripts/'
      preLoaderRoute: typeof AuthenticatedDashboardScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/scripts/$id': {
      id: '/_authenticated/dashboard/scripts/$id'
      path: '/dashboard/scripts/$id'
      fullPath: '/dashboard/scripts/$id'
      preLoaderRoute: typeof AuthenticatedDashboardScriptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/interactions': {
      id: '/api/public/discord/interactions'
      path: '/api/public/discord/interactions'
      fullPath: '/api/public/discord/interactions'
      preLoaderRoute: typeof ApiPublicDiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/register-commands': {
      id: '/api/public/discord/register-commands'
      path: '/api/public/discord/register-commands'
      fullPath: '/api/public/discord/register-commands'
      preLoaderRoute: typeof ApiPublicDiscordRegisterCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loader/$publicId': {
      id: '/api/public/loader/$publicId'
      path: '/api/public/loader/$publicId'
      fullPath: '/api/public/loader/$publicId'
      preLoaderRoute: typeof ApiPublicLoaderPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$publicId': {
      id: '/api/public/r/$publicId'
      path: '/api/public/r/$publicId'
      fullPath: '/api/public/r/$publicId'
      preLoaderRoute: typeof ApiPublicRPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/oauth/callback': {
      id: '/api/public/discord/oauth/callback'
      path: '/api/public/discord/oauth/callback'
      fullPath: '/api/public/discord/oauth/callback'
      preLoaderRoute: typeof ApiPublicDiscordOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/oauth/start': {
      id: '/api/public/discord/oauth/start'
      path: '/api/public/discord/oauth/start'
      fullPath: '/api/public/discord/oauth/start'
      preLoaderRoute: typeof ApiPublicDiscordOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardBatchesRoute: typeof AuthenticatedDashboardBatchesRoute
  AuthenticatedDashboardHwidRoute: typeof AuthenticatedDashboardHwidRoute
  AuthenticatedDashboardKeysRoute: typeof AuthenticatedDashboardKeysRoute
  AuthenticatedDashboardObfuscateRoute: typeof AuthenticatedDashboardObfuscateRoute
  AuthenticatedDashboardPanelsRoute: typeof AuthenticatedDashboardPanelsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardScriptsIdRoute: typeof AuthenticatedDashboardScriptsIdRoute
  AuthenticatedDashboardScriptsIndexRoute: typeof AuthenticatedDashboardScriptsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
  AuthenticatedDashboardBatchesRoute: AuthenticatedDashboardBatchesRoute,
  AuthenticatedDashboardHwidRoute: AuthenticatedDashboardHwidRoute,
  AuthenticatedDashboardKeysRoute: AuthenticatedDashboardKeysRoute,
  AuthenticatedDashboardObfuscateRoute: AuthenticatedDashboardObfuscateRoute,
  AuthenticatedDashboardPanelsRoute: AuthenticatedDashboardPanelsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardScriptsIdRoute: AuthenticatedDashboardScriptsIdRoute,
  AuthenticatedDashboardScriptsIndexRoute:
    AuthenticatedDashboardScriptsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsLoadingRoute: typeof DocsLoadingRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsLoadingRoute: DocsLoadingRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface FeaturesRouteChildren {
  FeaturesKeySystemGuiRoute: typeof FeaturesKeySystemGuiRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesKeySystemGuiRoute: FeaturesKeySystemGuiRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  CommandsRoute: CommandsRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  HowRoute: HowRoute,
  KeysRoute: KeysRoute,
  LoadingScreensRoute: LoadingScreensRoute,
  LoginRoute: LoginRoute,
  ObfuscatorsRoute: ObfuscatorsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TosRoute: TosRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiPublicObfuscateRoute: ApiPublicObfuscateRoute,
  ScriptsHostedPublicIdDotluaRoute: ScriptsHostedPublicIdDotluaRoute,
  ScriptsRawPublicIdDotluaRoute: ScriptsRawPublicIdDotluaRoute,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicDiscordInteractionsRoute: ApiPublicDiscordInteractionsRoute,
  ApiPublicDiscordRegisterCommandsRoute: ApiPublicDiscordRegisterCommandsRoute,
  ApiPublicLoaderPublicIdRoute: ApiPublicLoaderPublicIdRoute,
  ApiPublicRPublicIdRoute: ApiPublicRPublicIdRoute,
  ApiPublicDiscordOauthCallbackRoute: ApiPublicDiscordOauthCallbackRoute,
  ApiPublicDiscordOauthStartRoute: ApiPublicDiscordOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
